DROP TABLE IF EXISTS configuration;

CREATE TABLE configuration
(
    name VARCHAR(250) PRIMARY KEY,
    value VARCHAR(250) NOT NULL
);

INSERT INTO configuration
    (name, value)
VALUES
    ('MAX_AMOUNT', '50000'),
    ('MIN_AMOUNT', '0');

DROP TABLE IF EXISTS BANK_LINK;

CREATE TABLE BANK_LINK
(
    BANK_IP VARCHAR(45) PRIMARY KEY,
    BANK_CODE VARCHAR(2) NOT NULL
);

INSERT INTO BANK_LINK
    (BANK_IP, BANK_CODE)
VALUES
    ('0:0:0:0:0:0:0:1', '01');